### ISSUE TITLE
Diarization

### ISSUE THREAD

**Issue by nexuslux** [zh-plus/Open-Lyrics#3]
Does this or do you plan to add speaker recognition?

**Comment by zh-plus** [comment]
I'm not currently planning to add diarization support. Although the [whisperx](https://github.com/m-bain/whisperX) library natively supports Speaker Diarization, I don't think that identifying who is speaking will improve the quality of the final generated subtitles.

If you have any ideas on how to improve the subtitles using diarization, please feel free to discuss them here.
