### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by KonohaChen** [zh-plus/Open-Lyrics#5]
<img width="851" alt="image" src="https://github.com/zh-plus/Open-Lyrics/assets/70959924/c5e3b5a8-e429-4fc8-94f5-298ac12101c4">
Does someone know how to fix it?

**Comment by zh-plus** [comment]
It appears that the `model.bin` file was not downloaded successfully, as only 91% of it has been downloaded.

Try to delete the `C:\Users\19273\.cache\huggingface\hub\` directory and rerun the script.
