### ISSUE TITLE
AssertionError case sensitivity issue 

### ISSUE THREAD

**Issue by KonohaChen** [zh-plus/Open-Lyrics#6]
The exception looks like this:

AssertionError: Last split: ab not in ~~~~~AB~~~~~~

The low-case word cant match the upper-case word in the sentence. Exceptions may be caused by the abbreviation(e.g. BGM) or single letter in the sentences.

<img width="851" alt="image" src="https://github.com/zh-plus/Open-Lyrics/assets/70959924/437aa658-4508-4012-8c30-9803d79bd74d">

**Comment by zh-plus** [comment]
To install directly from the git repository, use the following command:

```shell
pip install git+https://github.com/zh-plus/Open-Lyrics
```

I have made recent commits to remove the assertion and fix a case-related issue. But these commits are not currently available on PYPI. I plan to create a new release this week that includes additional improvements.

**Comment by ClaireCJS** [comment]
I also had this error and your latest update fixed it for me!

**Comment by KonohaChen** [comment]
thank you for fixing the issues. One more thing, the latest version seems did not generate the lrc file but only json files, any idea?

**Comment by zh-plus** [comment]
> thank you for fixing the issues, it is working now. One more thing, the latest version seems did not generate the lrc file but only json files, any idea?

Fixed by https://github.com/zh-plus/Open-Lyrics/commit/7aee5fedcf4ad9c6cd55807d120c23db2a4b0b24
